 name-template: "v$RESOLVED_VERSION"
 tag-template: "v$RESOLVED_VERSION"
 categories:
   - title: "Features"
     labels:
       - "enhancement"
       - "feature"
   - title: "Bug Fixes"
     labels:
       - "bug"
   - title: "Maintenance"
     labels:
       - "chore"
       - "dependencies"
 change-template: "- $TITLE (#$NUMBER)"
 template: |
   ## Changes
   $CHANGES
